### ISSUE TITLE
darkmode ::after pour les liens externes

### ISSUE THREAD

**Issue by emirgc** [bibudem/wiki#1]
Affiche une icône pour les liens externes automatiquement, sauf celui menant vers le site des bibs.
Le problème, c'est qu'en passant au darkmode, la couleur reste la même. 
le stroke est hérité avec 'currentColor'. Le seul effet possible que j'ai réussi à appliquer est filter dans css.

[Piste de solution](https://codepen.io/noahblon/post/coloring-svgs-in-css-background-images?__cf_chl_captcha_tk__=w5G.Y.ZcnRzuGuareocexQKVwODqFuIv.jp9PxYbfKU-1641510101-0-gaNycGzNB30) pour changer la couleur lors du passage vers le darkmode. 

Ou mon approche n'est clairement pas bonne.

Voici le bout de code qui se trouve dans styleudem.css : 

```css

.md-content a[href^="http"]::after,
.md-content a[href^="https://"]::after
{
  content: "";
  width: 0.8em;
  height: 0.8em;
  margin-left: 0.3em;
  stroke: var(--md-typeset-a-color);
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' stroke='currentColor'  viewBox='0 0 16 16'%3E%3Cpath  d='M8.636 3.5a.5.5 0 0 0-.5-.5H1.5A1.5 1.5 0 0 0 0 4.5v10A1.5 1.5 0 0 0 1.5 16h10a1.5 1.5 0 0 0 1.5-1.5V7.864a.5.5 0 0 0-1 0V14.5a.5.5 0 0 1-.5.5h-10a.5.5 0 0 1-.5-.5v-10a.5.5 0 0 1 .5-.5h6.636a.5.5 0 0 0 .5-.5z'/%3E%3Cpath fill-rule='evenodd' d='M16 .5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0 0 1h3.793L6.146 9.146a.5.5 0 1 0 .708.708L15 1.707V5.5a.5.5 0 0 0 1 0v-5z'/%3E%3C/svg%3E");
  background-repeat: no-repeat;
  background-size: contain;
  display: inline-block;
}

.md-content a[href^="https://bib.umontreal.ca"]::after,
.md-content a[href^="https://calendrier.bib.umontreal.ca"]::after
{
  display: none !important;
}
```

**Comment by emirgc** [comment]
Piste de solution : 

```css

.md-content a[href^="http"]::after,
.md-content a[href^="https://"]::after
{
  content: "\00A0[↪]";
  /* autre symbole : ⇗  ↪︎ [↪] */
}
.md-content a[href^="https://bib.umontreal.ca"]::after,
.md-content a[href^="https://calendrier.bib.umontreal.ca"]::after
{
  display: none !important;
}
```
